<?php
/**
 * @file
 * os2web_accessibility.module
 * @author Yani Xu <yx@bellcom.dk>
 *
 */

/**
 * Implements hook_menu().
 */
function os2web_accessibility_menu() {
  $items['admin/config/os2web/handicap'] = array(
    'title' => 'Handicap settings',
    'description' => t('Setting for handicap pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_accessibility_setting_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['handicap'] = array(
    'title' => 'Handicap side',
    'page callback' => 'os2web_accessibility_frontpage',
    'access callback' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}
/**
 * Menu callback; presents the handicap settings page.
 */
function os2web_accessibility_setting_form() {
  $form['os2web_accessibility_setting'] = array(
    '#type' => 'fieldset',
    '#title' => t('Handicap frontpage'),
  );
  $form['os2web_accessibility_setting']['os2web_accessibility_node_content'] = array(
    '#type' => 'textfield',
    '#title' => t('Handicap node id'),
    '#default_value' => variable_get('os2web_accessibility_node_content'),
    '#size' => 3,
    '#maxlength' => 10,
    '#description' => t('Specify which node content show be then handicap front page.'),
  );
  $menu_options = array();
  $menu_options = menu_get_menus();

  $form['os2web_accessibility_setting']['os2web_accessibility_show_menus'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Menus to include in the handicap frontpage'),
    '#default_value' => variable_get('os2web_accessibility_show_menus', array()),
    '#options' => $menu_options,
    '#multiple' => TRUE,
  );
  return system_settings_form($form);
}

function os2web_accessibility_frontpage() {
  $nid = variable_get('os2web_accessibility_node_content');
  global $base_url;
  if (isset($nid)) {
    drupal_goto($base_url."/print/".$nid);
  }
}